---
# This is a basic workflow to lint the code base
name: "Code Base Linter"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions needed to run the workflow (top level)
permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Permissions needed to run the workflow (run level)
    permissions:
      contents: read
      statuses: write      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
          
      # Lint the changed Code Base
      - name: Lint Code Base 
        uses: github/super-linter@985ef206aaca4d560cb9ee2af2b42ba44adc1d55 #v4.10.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'workflow_dispatch'
               
      # Lint the complete Code Base
      - name: Lint Code Base 
        uses: github/super-linter@985ef206aaca4d560cb9ee2af2b42ba44adc1d55 #v4.10.0
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'workflow_dispatch'
